name: Build and Deploy Lean Docs

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          lfs: true

      - name: Install Lean
        run: |
          set -e
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s - -y --default-toolchain `cat ./lean-toolchain`
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build Documentation
        run: |
          set -e
          lake -Kenv=CI_BUILD clean
          lake -Kenv=CI_BUILD exe cache get
          lake -Kenv=CI_BUILD build
          lake -Kenv=CI_BUILD build Optlib:docs

      - name: Fix File Permissions
        run: |
          chmod -c -R +rX "./.lake/build/doc/" | while read line; do
            echo "::warning title=File permissions fixed::$line"
          done

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lean-docs
          path: ./.lake/build/doc/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
